### ISSUE TITLE
User Interactions

### ISSUE THREAD

**Issue by eshaghoshms** [ietf-wg-keytrans/draft-arch#3]
For Search: Would it make sense to add the following: " if the corresponding version does not exist, server should return a proof of non-inclusion"? I am also wondering if it is important to exclude batch update from the definition of Update (Note that this means that new values are added to the log immediately and are not queued for later insertion with a batch of other values.) since most scalable systems will do batching at least to some degree.

**Comment by Bren2010** [comment]
I don't think that we can support proofs of non-inclusion, as they require leaking too much information about the number of entries in the database.

I would support replacing language about "batching" with something that instead just captures the idea that there is no temporary SCT-style proof.

**Comment by eshaghoshms** [comment]
Isn't in crucial to support uniqueness of keys (i.e., given a certain username, the KT system should be able to return only one key as the latest)? I believe this uniqueness property implies support for non-inclusion proofs for the following reason. If there is no support for non-inclusion proof, the KT server could just claim (without any proof) that a certain username does not exist in the tree, when it actually does.

**Comment by kevinlewi** [comment]
Are we perhaps relying on owner signing for uniqueness of keys in the database? What if owner signing is not present -- how does the client know that the service provider isn't equivocating by showing two "valid" entries for the same username at the same epoch?

> I don't think that we can support proofs of non-inclusion, as they require leaking too much information about the number of entries in the database.

Hm, I'm also curious about why this is the case. How do proofs of non-inclusion leak more info about the # of entries in the database, beyond what proofs of inclusion do?

**Comment by eshaghoshms** [comment]
I’m curious why you think that a proof of inclusion is good enough for uniqueness? By proof-of-non-inclusion, I mean a cryptographic proof that the queried username does not exist in the database. To support uniqueness, the server should be able to provide a proof of the unique key corresponding to the queried username (if it exists in the database) or "empty string" to indicate that it does not. That is very different from no response from the server since the server is down. If the proof-of-non-inclusion is the same as no response, the server could exploit this to attack an account by distributing a fake key and proof-of-inclusion proof to some parties, while simply not responding to some other, for the same username. Did you mean something else by proof-of-non-inclusion?

> If a proof of inclusion is provided, then that does convey a guarantee of uniqueness: this is the only value corresponding to this key. Functionally (and from a security perspective), proofs of non-inclusion aren't very useful because receiving a proof of non-inclusion results in the same user experience as the KT server simply being down. Either way, there's no risk of impersonation because no cryptographic material was provided.

**Comment by Bren2010** [comment]
We have the same understanding of what a proof of non-inclusion is. What you're describing isn't an attack. If I'm a user trying to lookup the public key of my friend, the server refusing to respond doesn't allow impersonation. However, if I'm trying to do monitoring, the server refusing to respond to my monitor queries would need to be handled the same as any cryptographic reason that monitoring might fail (the detection of a fork / other illegal changes to the tree)

**Comment by Bren2010** [comment]
This conversation made me realize an interesting, privacy-preserving way to do proofs of non-inclusion for a key. When a user attempts to look up a key that doesn't exist, the server can insert version zero of the key with a special tombstone marker as its value. Subsequent lookups can reuse the same tombstone entry.

This obviously isn't something that makes sense to do for every application. As I said above, for most applications, a proof of non-inclusion and refusal to provide proof have the same UX and security value. But if a proof of non-inclusion would be particularly valuable, then this is an option.

**Comment by kevinlewi** [comment]
Ok, after re-reading carefully I think I understand how we are thinking about this differently. In Brendan's proposed architecture, each username is associated with a unique position in the sparse Merkle tree, which never changes, no matter how many times a new value is posted for that username.

In Esha's version, each leaf node in the Merkle tree is derived by the tuple (username || version #), so that updates to the value for a username increase this version # and result in different positions in the Merkle tree.

In Brendan's proposal, a proof of inclusion suffices for uniqueness because there is exactly one place to look for a username, regardless of how many times it was updated. Therefore, proof of non-inclusion is not needed.

> To provide a proof of non-inclusion in this same type of tree would require showing that a subtree is empty, and the height of the empty subtree leaks information about the number of populated leaves.

Btw Brendan, not sure if we understood this the same way, but: typically a proof of non-inclusion is not just a matter of showing that a subtree is empty. It instead consists of two proofs of inclusion of neighboring nodes in tree, which implies that since of them are in the tree, and they are neighbors, then nothing in between them exists (hence a proof of non-inclusion for a target node). Hope that makes sense...

Anyway, I think it would be useful for us to perhaps spawn off a separate discussion / issue around the design of having static nodes in the tree for usernames that do not change no matter how many times the username's value is updated. I think there are some interesting tradeoffs which this approach -- I'll create a new issue to host that discussion if you don't mind!
